---
- name: Stop Services, Subscribe, Update (Skip Jenkins), and Reboot
  hosts: all
  become: true
  vars:
    rh_username: "d.auttapol@gmail.com"
    rh_password: "B@dboy989"

  tasks:
    # ... (ส่วน 1-3 เหมือนเดิม ไม่ต้องแก้) ...
    # ... (Copy ส่วนบนจากไฟล์เดิมมาได้เลย) ...
    
    # -------------------------------------------------------
    # 1. Stop Services & Java
    # -------------------------------------------------------
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Stop Apache HTTPD (if running)
      ansible.builtin.service:
        name: httpd
        state: stopped
      when: 
        - "'httpd.service' in ansible_facts.services"
        - "ansible_facts.services['httpd.service'].state == 'running'"

    - name: Check if any Java process is running
      ansible.builtin.shell: pgrep java
      register: java_check
      ignore_errors: yes
      changed_when: false

    - name: Kill Java process (if found)
      ansible.builtin.shell: pkill java
      when: java_check.rc == 0

    # -------------------------------------------------------
    # 2. RHEL Subscription
    # -------------------------------------------------------
    - name: Register and auto-attach RHEL subscription
      redhat_subscription:
        state: present
        username: "{{ rh_username }}"
        password: "{{ rh_password }}"
        auto_attach: true

    # -------------------------------------------------------
    # 3. Update Patch
    # -------------------------------------------------------
    - name: Install dnf-utils (Prerequisite for reboot check)
      ansible.builtin.dnf:
        name: dnf-utils
        state: present

    - name: Upgrade all packages (Skip Jenkins to avoid GPG Error)
      ansible.builtin.dnf:
        name: "*"           
        state: latest
        exclude: jenkins*
      register: dnf_output

    # [จุดที่แก้ไข] ใช้ to_nice_yaml เพื่อจัดรูปแบบให้อ่านง่ายเป็นบรรทัดๆ
    - name: Show updated packages list
      ansible.builtin.debug:
        msg: 
          - "======================================================="
          - "  UPDATE SUMMARY FOR HOST: {{ inventory_hostname }}"
          - "======================================================="
          - "{{ dnf_output.results | to_nice_yaml }}"
          - "======================================================="
      when: dnf_output.changed

    # -------------------------------------------------------
    # 4. Reboot Logic
    # -------------------------------------------------------
    - name: Check if reboot is required
      ansible.builtin.command: needs-restarting -r
      register: reboot_required
      ignore_errors: yes
      changed_when: false
      failed_when: reboot_required.rc != 0 and reboot_required.rc != 1

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Rebooting system after Maintenance"
        connect_timeout: 5
        reboot_timeout: 600   
        pre_reboot_delay: 0
        post_reboot_delay: 30 
      when: reboot_required.rc == 1
